# Generated by Django 5.1.7 on 2025-03-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmes.genero'),
        ),
    ]
