# Generated by Django 5.1.7 on 2025-03-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_genero_alter_filme_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
