# Generated by Django 5.1.7 on 2025-04-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filme_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='descricao',
            new_name='nome',
        ),
    ]
